
releases:
  - name: kube-descheduler
    chart: kube-descheduler
    namespace: cluster-service-kube-descheduler
    wait: true
    timeout: 120
    values:
      - environments/{{ env "ENVIRONMENT" | default "stage" }}/values.yaml
      - image:
          tag: '{{ env "IMAGE_TAG" | default "latest-master" }}'
          repository: '{{ env "ECR_REPOSITORY_URL" }}'